Sprint_2
nessensis/qa_python pull request #2
Opened 2023-07-02 17:46 UTC by nessensis

Задание в изначальном файле main.py отличалось от задания в практикуме, поэтому я его изменила и он тоже в коммите

2023-07-03 19:32 UTC, kadirovgm requested changes

2023-07-03 19:32 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('name, genre', [['Рубеус Хагрид и зря я это сказал', 'Комедии']])
нужно исправить: зачем здесь параметризация, если книга одна и жанр один?

2023-07-03 19:32 UTC, kadirovgm commented on main.py
> +        self.books_genre = {}
спасибо, что изменила задание, в коде не успели задания появиться

2023-07-03 19:32 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_genre(name) == genre
верно)

2023-07-03 19:32 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_with_specific_genre('Ужасы') == ['Рон Уизли и пауки заставляют танцевать']
супер)

2023-07-03 19:32 UTC, kadirovgm commented on tests.py
> +    def test_get_books_genre_show_actual_books_genre(self):
нужно исправить: такой тест у тебя уже есть выше: `test_add_new_book_add_two_books`

2023-07-03 19:32 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_for_children() != ['Рон Уизли и пауки заставляют танцевать']
нужно исправить: нам нужно делать явный тест, а не косвенный, то, что в выдаче нет этой книги, это верно, но не означает, что там нет другой (сейчас это конечно невозможно, но в общем случае возможно)

поэтому здесь можно было бы проверить, что `get_books_for_children` возвращает именно книгу с жанром "комедия", то есть другюу книгу

2023-07-03 19:32 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books() == ['Гермиона Грейнджер и я же говорила']
верно

2023-07-03 19:32 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books() == []
верно, также можно воспользоваться конструкцией `in/not in`

2023-07-03 20:21 UTC, nessensis commented on tests.py
> +    @pytest.mark.parametrize('name, genre', [['Рубеус Хагрид и зря я это сказал', 'Комедии']])
Добрый вечер! 
В задании к проекту один из критериев - использование параметризации, но я не увидела какому из моих тестов она вообще нужна и просто положила к любому, "чтобы было"))
Я попробую придумать новый тест вместо дубля, где она будет уместна

2023-07-04 18:36 UTC, nessensis commented on tests.py
> +    @pytest.mark.parametrize('name, genre', [['Рубеус Хагрид и зря я это сказал', 'Комедии']])
исправила ошибки и добавила тест на граничные значения с использованием параметризации

2023-07-04 21:29 UTC, kadirovgm requested changes

2023-07-04 21:29 UTC, kadirovgm commented on tests.py
> +    def test_add_new_book_not_add_book_name_more_than_40_symbols(self, name):
нужно исправить: думаю здесь излишне проверять параметризацией, так как обе тестовые книги имеют длину более 40 символов и по сути являются элементами одного класса эквивалентности
конкретно здесь хватило бы проверить на одном примере

2023-07-04 21:29 UTC, kadirovgm commented on tests.py
> +    def test_set_book_genre_set_genre_to_new_books(self):
можно лучше: параметризацию можно применить на метод `set_book_genre`
У нас есть условие которое нужно проверить, так как `set_book_genre` установит жанр только если:
1. Книга есть в словаре `books_genre`
2. Ее жанр входит в список `genre`

параметризованными жанрами могут быть те, которых нет в этом списке `genre`, а также книги которых нет в словаре. Можно также комбинировать параметры, чтобы выполнялось только одно условие

2023-07-04 21:29 UTC, kadirovgm commented on tests.py
>      def test_get_books_for_children_not_show_horror_books(self):
нужно исправить: думаю параметризацию можно применить тут: например нам явно надо проверить, что Ужасы и Детективы детям показывать нельзя (эти две данные можно параметризировать)

2023-07-05 21:49 UTC, kadirovgm approved these changes

2023-07-12 19:21 UTC, merged